// Builds src/pantone-c.js from the pantonr package's coated lists (MIT, https://github.com/thompsongl/pantonr).
//   npm pack pantonr && tar xzf pantonr-*.tgz && node scripts/build-pantone.mjs package/dist
// The colour values are Pantone's, converted from its old library files: they are approximations for matching a colour to the nearest chip,
// never a substitute for the physical Pantone Formula Guide (Solid Coated), which the factory checks against.
import { readFileSync, writeFileSync } from 'node:fs';
const dir = process.argv[2] || 'package/dist';
const load = f => JSON.parse(readFileSync(`${dir}/${f}`, 'utf8'));
const tidy = n => String(n).replace(/^PANTONE\s+/i, '').replace(/\s+/g, ' ').trim();
const kinds = [['solid', 'pantone_coated.json'], ['pastel', 'pantone_pastels_neons_coated.json'], ['metallic', 'pantone_metallic_coated.json']];
const rows = []; const seen = new Set();
for (const [kind, file] of kinds) for (const v of Object.values(load(file))) {
  const name = tidy(v.name); if (!/ C$/.test(name) || seen.has(name)) continue; seen.add(name);
  rows.push([name, v.hex.replace('#', ''), kind === 'solid' ? 0 : kind === 'pastel' ? 1 : 2]);
}
const out = `// Pantone Solid Coated ("C") colours, for matching a colour to the nearest Pantone C chip. ${rows.length} entries: solid coated, pastel and neon coated, metallic coated.
// Generated by scripts/build-pantone.mjs from the pantonr package (MIT licence, Greg Thompson). The values are approximations converted from Pantone's
// older library files: use them to suggest a chip, and have the factory confirm against the physical Pantone Formula Guide. PANTONE is a registered trademark of Pantone LLC.
// Each row: [name, hex without #, kind: 0 solid · 1 pastel/neon · 2 metallic]
(function (root) {
  'use strict';
  const T = ${JSON.stringify(rows)};
  const lin = v => { v /= 255; return v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
  const f = t => t > 216 / 24389 ? Math.cbrt(t) : (24389 / 27 * t + 16) / 116;
  function lab(hex) {
    const n = parseInt(String(hex).replace('#', ''), 16); if (!Number.isFinite(n)) return null;
    const R = lin(n >> 16 & 255), G = lin(n >> 8 & 255), B = lin(n & 255);
    const x = f((R * 0.4124 + G * 0.3576 + B * 0.1805) / 0.95047), y = f(R * 0.2126 + G * 0.7152 + B * 0.0722), z = f((R * 0.0193 + G * 0.1192 + B * 0.9505) / 1.08883);
    return [116 * y - 16, 500 * (x - y), 200 * (y - z)];
  }
  // CIEDE2000
  function de2000(p, q) {
    const rad = Math.PI / 180, deg = 180 / Math.PI, [L1, a1, b1] = p, [L2, a2, b2] = q;
    const C1 = Math.hypot(a1, b1), C2 = Math.hypot(a2, b2), Cb = (C1 + C2) / 2, G = 0.5 * (1 - Math.sqrt(Math.pow(Cb, 7) / (Math.pow(Cb, 7) + Math.pow(25, 7))));
    const A1 = (1 + G) * a1, A2 = (1 + G) * a2, Cp1 = Math.hypot(A1, b1), Cp2 = Math.hypot(A2, b2);
    const h = (b, a) => { if (!b && !a) return 0; const v = Math.atan2(b, a) * deg; return v < 0 ? v + 360 : v; }, hp1 = h(b1, A1), hp2 = h(b2, A2);
    const dL = L2 - L1, dC = Cp2 - Cp1; let dh = 0; if (Cp1 * Cp2) { dh = hp2 - hp1; if (dh > 180) dh -= 360; else if (dh < -180) dh += 360; }
    const dH = 2 * Math.sqrt(Cp1 * Cp2) * Math.sin(dh * rad / 2), Lb = (L1 + L2) / 2, Cpb = (Cp1 + Cp2) / 2;
    let hb = hp1 + hp2; if (Cp1 * Cp2) { hb = Math.abs(hp1 - hp2) > 180 ? (hp1 + hp2 + (hp1 + hp2 < 360 ? 360 : -360)) / 2 : (hp1 + hp2) / 2; }
    const T2 = 1 - 0.17 * Math.cos((hb - 30) * rad) + 0.24 * Math.cos(2 * hb * rad) + 0.32 * Math.cos((3 * hb + 6) * rad) - 0.2 * Math.cos((4 * hb - 63) * rad);
    const dT = 30 * Math.exp(-Math.pow((hb - 275) / 25, 2)), Rc = 2 * Math.sqrt(Math.pow(Cpb, 7) / (Math.pow(Cpb, 7) + Math.pow(25, 7)));
    const Sl = 1 + 0.015 * Math.pow(Lb - 50, 2) / Math.sqrt(20 + Math.pow(Lb - 50, 2)), Sc = 1 + 0.045 * Cpb, Sh = 1 + 0.015 * Cpb * T2, Rt = -Math.sin(2 * dT * rad) * Rc;
    return Math.sqrt(Math.pow(dL / Sl, 2) + Math.pow(dC / Sc, 2) + Math.pow(dH / Sh, 2) + Rt * (dC / Sc) * (dH / Sh));
  }
  const LABS = T.map(r => lab(r[1]));
  // The nearest Pantone C chips to a colour: [{ code: "PANTONE 485 C", name: "485 C", hex, deltaE }]. kinds: which lists to search (default solid coated; metallics only when asked).
  function nearest(hex, { n = 1, kinds = [0, 1] } = {}) {
    const q = lab(hex); if (!q) return [];
    const out = [];
    for (let i = 0; i < T.length; i++) { if (!kinds.includes(T[i][2])) continue; out.push({ i, d: de2000(q, LABS[i]) }); }
    out.sort((a, b) => a.d - b.d);
    return out.slice(0, n).map(o => ({ code: 'PANTONE ' + T[o.i][0], name: T[o.i][0], hex: '#' + T[o.i][1], deltaE: Math.round(o.d * 10) / 10 }));
  }
  // One code for a colour. Foil and metallic colours cannot be matched by their screen colour (a metallic chip is a dull grey on screen), so a name or note
  // that says silver, gold or copper gets the standard metallic chip for it: 877 C silver, 871 C gold, 876 C copper.
  const METAL = [[/\\bsilver\\b|\\bchrome\\b|\\bgunmetal\\b/i, '877 C'], [/\\bgold\\b/i, '871 C'], [/\\bcopper\\b|\\bbronze\\b/i, '876 C']];
  function code(hex, { hint = '' } = {}) {
    for (const [re, chip] of METAL) if (re.test(hint) && T.some(r => r[0] === chip)) return 'PANTONE ' + chip;
    const m = nearest(hex, { kinds: [0, 1] })[0];
    return m ? m.code : '';
  }
  const isC = s => /^PANTONE\\s+.+\\sC$/i.test(String(s || '').trim());
  const api = { nearest, code, isC, lab, de2000, count: T.length };
  root.FBPantone = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;
writeFileSync('src/pantone-c.js', out);
console.log('wrote src/pantone-c.js', rows.length, 'entries', (out.length / 1024).toFixed(0) + ' KB');
